"""Application name no longer unique in passwords table, so that many users can have passwords for a single application

Revision ID: 7779cf0fd1b8
Revises: 08a2201a68ab
Create Date: 2024-01-20 12:01:04.055465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7779cf0fd1b8'
down_revision = '08a2201a68ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.drop_index('appli_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('passwords', schema=None) as batch_op:
        batch_op.create_index('appli_name', ['appli_name'], unique=True)

    # ### end Alembic commands ###
