"""Added a Users table, registration and login form

Revision ID: a1e75cb39609
Revises: f6c29f4c55f3
Create Date: 2024-01-12 17:42:09.873908

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a1e75cb39609'
down_revision = 'f6c29f4c55f3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('username', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('date_created', sa.DateTime(), nullable=True))
        batch_op.drop_index('appli_name')
        batch_op.drop_column('user')
        batch_op.drop_column('appli_user_name')
        batch_op.drop_column('appli_name')
        batch_op.drop_column('date_added')
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('date_added', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('appli_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('appli_user_name', mysql.VARCHAR(length=200), nullable=False))
        batch_op.add_column(sa.Column('user', mysql.VARCHAR(length=200), nullable=False))
        batch_op.create_index('appli_name', ['appli_name'], unique=True)
        batch_op.drop_column('date_created')
        batch_op.drop_column('username')

    # ### end Alembic commands ###
